version: '3'
services:
  spring-jpa:
    image: propietarios
    ports:
      - "8081:8081"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 8jJ8cC8gVEqtVJs7ntkw
      MYSQL_DATABASE: bzif0dgvzjp0ltbihfzv
      MYSQL_USER: uobhlq41ybfzh4h3
    ports:
      - "3306:3306"
