spring:
  datasource:
    url: jdbc:mysql://brmq2i6wv3t0eid8lct2-mysql.services.clever-cloud.com:3306/brmq2i6wv3t0eid8lct2
    username: uaezul0idy3wecfz
    password: r4EophLAFcZEvQk8OEkV
  hibernate:
    ddl-auto: update
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
