spring:
  datasource:
    url: jdbc:mysql://bzif0dgvzjp0ltbihfzv-mysql.services.clever-cloud.com:3306/bzif0dgvzjp0ltbihfzv?useSSL=false
    username: uobhlq41ybfzh4h3
    password: 8jJ8cC8gVEqtVJs7ntkw
